version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/docker-worspace/docker-app/data/mysql:/var/lib/mysql
      - /var/docker-worspace/docker-app/env/services/mysql/conf.d:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fecshop
    networks:
      - code-network
networks:
  code-network:
    driver: bridge